### ISSUE TITLE
Moving license to own file

### ISSUE THREAD

**Issue by shivan-s** [ezstarr/TimeBot#2]
It's good there is an MIT license but I propose moving it to a single file `LICENSE` rather than being in docstring of each `.py` file.

**Comment by shivan-s** [comment]
Never mind, I just realised there is a `LICENSE` file. But do we need it present in each .py file?

**Comment by EvieePy** [comment]
It is recommended to put the MIT license in every significant piece of code much like other licenses that have a short per file version.

**Comment by shivan-s** [comment]
Ahh, I didn't know this. Thank you.

**Comment by shivan-s** [comment]
Closing this as the answer is satisfactory :)
